apiVersion: v1
kind: Service
metadata:
  name: greengram-feed
  namespace: greengram
  labels:
    app: greengram-feed
spec:
  selector:
    app: greengram-feed
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP   
