apiVersion: apps/v1
kind: Deployment
metadata:
  name: scg-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scg-app
  template:
    metadata:
      labels:
        app: scg-app
    spec:
      containers:
      - name: scg-app
        image: harbor.greenart.n-e.kr/greengram/scg:37
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: harbor-docker-config