apiVersion: v1
kind: Service
metadata:
  name: front-app-service
  namespace: greengram
spec:
  selector:
    app: front-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30890
  type: NodePort
